require('dotenv').config({ path: require('path').join(__dirname, '..', '.env') });
const mongoose = require('mongoose');
const College = require('../models/College');

const MONGO_URI = process.env.MONGO_URI;

const colleges = [
  // ─── ENGINEERING - JEE/CET ───────────────────────────────────────────
  {
    name: 'Indian Institute of Technology Bombay',
    shortName: 'IIT Bombay',
    city: 'Mumbai', district: 'Mumbai',
    address: 'Powai, Mumbai - 400076',
    affiliation: 'Autonomous (IIT)',
    website: 'https://www.iitb.ac.in',
    type: 'Government',
    streams: ['Engineering'],
    exams: ['JEE'],
    cutoffs: { jee: 98, cet: null, neet: null, hsc: null },
    fees: { engineering: 225000 },
    ranking: 1, rating: 4.9, established: 1958, totalSeats: 880,
    description: 'Premier engineering institute, ranked #1 in India.',
    lat: 19.1334, lng: 72.9133,
  },
  {
    name: 'Visvesvaraya National Institute of Technology',
    shortName: 'VNIT Nagpur',
    city: 'Nagpur', district: 'Nagpur',
    address: 'South Ambazari Road, Nagpur - 440010',
    affiliation: 'Autonomous (NIT)',
    website: 'https://vnit.ac.in',
    type: 'Government',
    streams: ['Engineering'],
    exams: ['JEE'],
    cutoffs: { jee: 92, cet: null, neet: null, hsc: null },
    fees: { engineering: 155000 },
    ranking: 2, rating: 4.6, established: 1960, totalSeats: 700,
    description: 'National Institute of Technology known for its academic excellence in Central India.',
    lat: 21.1214, lng: 79.0524,
  },
  {
    name: 'College of Engineering Pune',
    shortName: 'COEP',
    city: 'Pune', district: 'Pune',
    address: 'Wellesley Road, Shivajinagar, Pune - 411005',
    affiliation: 'Savitribai Phule Pune University',
    website: 'https://www.coep.org.in',
    type: 'Government',
    streams: ['Engineering'],
    exams: ['JEE', 'CET'],
    cutoffs: { jee: 85, cet: 155, neet: null, hsc: null },
    fees: { engineering: 95000 },
    ranking: 3, rating: 4.7, established: 1854, totalSeats: 480,
    description: 'One of the oldest and most prestigious engineering colleges in Asia.',
    lat: 18.5308, lng: 73.8474,
  },
  {
    name: 'Veermata Jijabai Technological Institute',
    shortName: 'VJTI',
    city: 'Mumbai', district: 'Mumbai',
    address: 'H R Mahajani Road, Matunga, Mumbai - 400019',
    affiliation: 'Mumbai University',
    website: 'https://vjti.ac.in',
    type: 'Government',
    streams: ['Engineering'],
    exams: ['JEE', 'CET'],
    cutoffs: { jee: 80, cet: 150, neet: null, hsc: null },
    fees: { engineering: 85000 },
    ranking: 4, rating: 4.6, established: 1887, totalSeats: 540,
    description: 'Historic engineering institution with strong industry connections in Mumbai.',
    lat: 19.0219, lng: 72.8560,
  },
  {
    name: 'Institute of Chemical Technology',
    shortName: 'ICT Mumbai',
    city: 'Mumbai', district: 'Mumbai',
    address: 'Nathalal Parekh Marg, Matunga, Mumbai - 400019',
    affiliation: 'Autonomous (Deemed University)',
    website: 'https://www.ictmumbai.edu.in',
    type: 'Deemed',
    streams: ['Engineering'],
    exams: ['JEE', 'CET'],
    cutoffs: { jee: 78, cet: 148, neet: null, hsc: null },
    fees: { engineering: 110000 },
    ranking: 5, rating: 4.5, established: 1933, totalSeats: 360,
    description: 'Leading institute for chemical engineering and technology.',
    lat: 19.0254, lng: 72.8544,
  },
  {
    name: 'Sardar Patel Institute of Technology',
    shortName: 'SPIT Mumbai',
    city: 'Mumbai', district: 'Mumbai',
    address: 'Bhavans Campus, Munshi Nagar, Andheri West, Mumbai - 400058',
    affiliation: 'Mumbai University',
    website: 'https://www.spit.ac.in',
    type: 'Autonomous',
    streams: ['Engineering'],
    exams: ['JEE', 'CET'],
    cutoffs: { jee: 72, cet: 140, neet: null, hsc: null },
    fees: { engineering: 150000 },
    ranking: 6, rating: 4.4, established: 1962, totalSeats: 360,
    description: 'Top autonomous engineering institute in Mumbai with excellent placement record.',
    lat: 19.1192, lng: 72.8366,
  },
  {
    name: 'Pune Institute of Computer Technology',
    shortName: 'PICT Pune',
    city: 'Pune', district: 'Pune',
    address: 'Survey No. 27, Near Trimurti Chowk, Dhankawadi, Pune - 411043',
    affiliation: 'Savitribai Phule Pune University',
    website: 'https://pict.edu',
    type: 'Private',
    streams: ['Engineering'],
    exams: ['JEE', 'CET'],
    cutoffs: { jee: 70, cet: 138, neet: null, hsc: null },
    fees: { engineering: 180000 },
    ranking: 7, rating: 4.4, established: 1983, totalSeats: 480,
    description: 'Renowned for CS and IT programs with 100% placement support.',
    lat: 18.4570, lng: 73.8602,
  },
  {
    name: 'MIT World Peace University',
    shortName: 'MIT-WPU Pune',
    city: 'Pune', district: 'Pune',
    address: 'Paud Road, Kothrud, Pune - 411038',
    affiliation: 'MIT-WPU University',
    website: 'https://mitwpu.edu.in',
    type: 'Private',
    streams: ['Engineering', 'Management', 'Pharmacy'],
    exams: ['JEE', 'CET'],
    cutoffs: { jee: 65, cet: 128, neet: null, hsc: null },
    fees: { engineering: 310000, management: 250000 },
    ranking: 8, rating: 4.3, established: 1983, totalSeats: 1200,
    description: 'Renowned private university in Pune with global exposure.',
    lat: 18.5183, lng: 73.8150,
  },
  {
    name: 'Vishwakarma Institute of Technology',
    shortName: 'VIT Pune',
    city: 'Pune', district: 'Pune',
    address: 'Bibwewadi, Pune - 411037',
    affiliation: 'Savitribai Phule Pune University',
    website: 'https://vit.edu',
    type: 'Autonomous',
    streams: ['Engineering'],
    exams: ['JEE', 'CET'],
    cutoffs: { jee: 62, cet: 125, neet: null, hsc: null },
    fees: { engineering: 195000 },
    ranking: 9, rating: 4.2, established: 1983, totalSeats: 600,
    description: 'Highly ranked engineering college in Pune known for technical events.',
    lat: 18.4726, lng: 73.8637,
  },
  {
    name: 'KJ Somaiya College of Engineering',
    shortName: 'KJSCE Mumbai',
    city: 'Mumbai', district: 'Mumbai',
    address: 'Vidyavihar, Mumbai - 400077',
    affiliation: 'Somaiya Vidyavihar University',
    website: 'https://kjsce.somaiya.edu',
    type: 'Private',
    streams: ['Engineering'],
    exams: ['JEE', 'CET'],
    cutoffs: { jee: 68, cet: 132, neet: null, hsc: null },
    fees: { engineering: 220000 },
    ranking: 10, rating: 4.3, established: 1983, totalSeats: 540,
    description: 'Top private engineering college in Mumbai with lush green campus.',
    lat: 19.0785, lng: 72.9035,
  },

  // ─── MEDICAL - NEET ───────────────────────────────────────────────────
  {
    name: 'Armed Forces Medical College',
    shortName: 'AFMC Pune',
    city: 'Pune', district: 'Pune',
    address: 'Wanowrie, Pune - 411040',
    affiliation: 'Maharashtra University of Health Sciences',
    website: 'https://afmc.nic.in',
    type: 'Government',
    streams: ['Medical'],
    exams: ['NEET'],
    cutoffs: { jee: null, cet: null, neet: 660, hsc: null },
    fees: { medical: 32000 },
    ranking: 1, rating: 4.9, established: 1948, totalSeats: 150,
    description: 'Premier medical institute for training for the Armed Forces.',
    lat: 18.5024, lng: 73.8894,
  },
  {
    name: 'All India Institute of Medical Sciences Nagpur',
    shortName: 'AIIMS Nagpur',
    city: 'Nagpur', district: 'Nagpur',
    address: 'MIHAN, Nagpur - 441108',
    affiliation: 'Autonomous (AIIMS)',
    website: 'https://aiimsnagpur.edu.in',
    type: 'Government',
    streams: ['Medical'],
    exams: ['NEET'],
    cutoffs: { jee: null, cet: null, neet: 680, hsc: null },
    fees: { medical: 6000 },
    ranking: 2, rating: 4.8, established: 2018, totalSeats: 125,
    description: 'One of the prestigious AIIMS institutes in India.',
    lat: 21.0183, lng: 79.0205,
  },
  {
    name: 'Grant Medical College & Sir JJ Group of Hospitals',
    shortName: 'GMC Mumbai',
    city: 'Mumbai', district: 'Mumbai',
    address: 'Byculla, Mumbai - 400008',
    affiliation: 'Maharashtra University of Health Sciences',
    website: 'https://www.grantmedicalcollege.org',
    type: 'Government',
    streams: ['Medical'],
    exams: ['NEET'],
    cutoffs: { jee: null, cet: null, neet: 640, hsc: null },
    fees: { medical: 35000 },
    ranking: 3, rating: 4.8, established: 1845, totalSeats: 250,
    description: 'One of the oldest and most prestigious medical colleges in India.',
    lat: 18.9735, lng: 72.8283,
  },
  {
    name: 'Seth G.S. Medical College & KEM Hospital',
    shortName: 'KEM Hospital',
    city: 'Mumbai', district: 'Mumbai',
    address: 'Parel, Mumbai - 400012',
    affiliation: 'Maharashtra University of Health Sciences',
    website: 'https://www.kem.edu',
    type: 'Government',
    streams: ['Medical'],
    exams: ['NEET'],
    cutoffs: { jee: null, cet: null, neet: 645, hsc: null },
    fees: { medical: 35000 },
    ranking: 4, rating: 4.8, established: 1926, totalSeats: 250,
    description: 'Premier medical college affiliated to the iconic KEM Hospital.',
    lat: 19.0010, lng: 72.8403,
  },
  {
    name: 'B.J. Medical College',
    shortName: 'BJMC Pune',
    city: 'Pune', district: 'Pune',
    address: 'Sassoon Road, Pune - 411001',
    affiliation: 'Maharashtra University of Health Sciences',
    website: 'https://www.bjmc.edu.in',
    type: 'Government',
    streams: ['Medical'],
    exams: ['NEET'],
    cutoffs: { jee: null, cet: null, neet: 630, hsc: null },
    fees: { medical: 35000 },
    ranking: 5, rating: 4.7, established: 1946, totalSeats: 250,
    description: 'Top government medical college in Pune with Sassoon Hospital attachment.',
    lat: 18.5196, lng: 73.8554,
  },
  {
    name: 'Dr. DY Patil Medical College',
    shortName: 'DY Patil Medical',
    city: 'Pune', district: 'Pune',
    address: 'Sant Tukaram Nagar, Pimpri, Pune - 411018',
    affiliation: 'Dr. DY Patil Deemed University',
    website: 'https://www.dypatil.edu',
    type: 'Deemed',
    streams: ['Medical', 'Pharmacy'],
    exams: ['NEET'],
    cutoffs: { jee: null, cet: null, neet: 550, hsc: null },
    fees: { medical: 1200000, pharmacy: 150000 },
    ranking: 15, rating: 4.1, established: 1996, totalSeats: 250,
    description: 'Well-equipped private medical college with state-of-the-art hospital.',
    lat: 18.6271, lng: 73.8007,
  },
  {
    name: 'Bharati Vidyapeeth Deemed University Medical College',
    shortName: 'BVDU Medical',
    city: 'Pune', district: 'Pune',
    address: 'Dhankawadi, Pune - 411043',
    affiliation: 'Bharati Vidyapeeth University',
    website: 'https://mcpune.bharatividyapeeth.edu',
    type: 'Deemed',
    streams: ['Medical'],
    exams: ['NEET'],
    cutoffs: { jee: null, cet: null, neet: 540, hsc: null },
    fees: { medical: 2100000 },
    ranking: 18, rating: 4.0, established: 1989, totalSeats: 150,
    description: 'Reputed deemed university medical college in Pune.',
    lat: 18.4554, lng: 73.8496,
  },

  // ─── ARTS / SCIENCE / COMMERCE - HSC ─────────────────────────────────
  {
    name: 'Fergusson College',
    shortName: 'Fergusson',
    city: 'Pune', district: 'Pune',
    address: 'Fergusson College Road, Shivajinagar, Pune - 411004',
    affiliation: 'Savitribai Phule Pune University',
    website: 'https://www.fergusson.edu',
    type: 'Autonomous',
    streams: ['Science', 'Commerce', 'Arts'],
    exams: ['HSC'],
    cutoffs: { jee: null, cet: null, neet: null, hsc: 80 },
    fees: { science: 25000, commerce: 20000, arts: 18000 },
    ranking: 1, rating: 4.7, established: 1885, totalSeats: 1200,
    description: 'One of the oldest and most coveted liberal arts and science colleges in India.',
    lat: 18.5220, lng: 73.8397,
  },
  {
    name: 'St. Xavier\'s College Mumbai',
    shortName: 'Xavier\'s Mumbai',
    city: 'Mumbai', district: 'Mumbai',
    address: '5, Mahapalika Marg, Mumbai - 400001',
    affiliation: 'Mumbai University',
    website: 'https://www.xaviers.edu',
    type: 'Autonomous',
    streams: ['Science', 'Commerce', 'Arts'],
    exams: ['HSC'],
    cutoffs: { jee: null, cet: null, neet: null, hsc: 85 },
    fees: { science: 30000, commerce: 25000, arts: 22000 },
    ranking: 2, rating: 4.8, established: 1869, totalSeats: 1500,
    description: 'Iconic autonomous institution known for academic excellence and vibrant campus life.',
    lat: 18.9382, lng: 72.8314,
  },
  {
    name: 'Elphinstone College',
    shortName: 'Elphinstone',
    city: 'Mumbai', district: 'Mumbai',
    address: 'Fort, Mumbai - 400032',
    affiliation: 'Mumbai University',
    website: 'https://www.elphinstonecollege.ac.in',
    type: 'Government',
    streams: ['Science', 'Arts', 'Commerce'],
    exams: ['HSC'],
    cutoffs: { jee: null, cet: null, neet: null, hsc: 75 },
    fees: { science: 12000, commerce: 10000, arts: 9000 },
    ranking: 3, rating: 4.5, established: 1856, totalSeats: 1000,
    description: 'Historic government college with excellent faculty and affordable education.',
    lat: 18.9298, lng: 72.8301,
  },
  {
    name: 'Symbiosis College of Arts and Commerce',
    shortName: 'SCAC Pune',
    city: 'Pune', district: 'Pune',
    address: 'Senapati Bapat Road, Pune - 411004',
    affiliation: 'Savitribai Phule Pune University',
    website: 'https://www.symbiosiscacpune.com',
    type: 'Private',
    streams: ['Arts', 'Commerce'],
    exams: ['HSC'],
    cutoffs: { jee: null, cet: null, neet: null, hsc: 70 },
    fees: { commerce: 45000, arts: 40000 },
    ranking: 5, rating: 4.3, established: 1983, totalSeats: 800,
    description: 'Popular college with vibrant campus life and excellent commerce programs.',
    lat: 18.5204, lng: 73.8346,
  },
];

async function seedDB() {
  try {
    console.log('🔌 Connecting to MongoDB Atlas...');
    await mongoose.connect(MONGO_URI);
    console.log('✅ Connected to MongoDB Atlas');

    await College.deleteMany({});
    console.log('🗑️  Cleared existing colleges');

    const inserted = await College.insertMany(colleges);
    console.log(`🎉 Successfully seeded ${inserted.length} colleges!`);

    await mongoose.disconnect();
    console.log('🔌 Disconnected from MongoDB');
    process.exit(0);
  } catch (err) {
    console.error('❌ Seed error:', err);
    process.exit(1);
  }
}

seedDB();
