require('dotenv').config({ path: require('path').join(__dirname, '..', '.env') });
const mongoose = require('mongoose');
const College = require('../models/College');

const MONGO_URI = process.env.MONGO_URI;

const colleges = [
  // ─── ENGINEERING - JEE/CET ───────────────────────────────────────────
  {
    name: 'Indian Institute of Technology Bombay',
    shortName: 'IIT Bombay',
    city: 'Mumbai', district: 'Mumbai',
    address: 'Powai, Mumbai - 400076',
    affiliation: 'Autonomous (IIT)',
    website: 'https://www.iitb.ac.in',
    type: 'Government',
    streams: ['Engineering'],
    exams: ['JEE'],
    cutoffs: { jee: 98, cet: null, neet: null, hsc: null },
    fees: { engineering: 225000 },
    ranking: 1, rating: 4.9, established: 1958, totalSeats: 880,
    description: 'Premier engineering institute, ranked #1 in India.',
    lat: 19.1334, lng: 72.9133,
  },
  {
    name: 'College of Engineering Pune',
    shortName: 'COEP',
    city: 'Pune', district: 'Pune',
    address: 'Wellesley Road, Shivajinagar, Pune - 411005',
    affiliation: 'Savitribai Phule Pune University',
    website: 'https://www.coep.org.in',
    type: 'Government',
    streams: ['Engineering'],
    exams: ['JEE', 'CET'],
    cutoffs: { jee: 85, cet: 155, neet: null, hsc: null },
    fees: { engineering: 95000 },
    ranking: 2, rating: 4.7, established: 1854, totalSeats: 480,
    description: 'One of the oldest and most prestigious engineering colleges in Asia.',
    lat: 18.5308, lng: 73.8474,
  },
  {
    name: 'Veermata Jijabai Technological Institute',
    shortName: 'VJTI',
    city: 'Mumbai', district: 'Mumbai',
    address: 'H R Mahajani Road, Matunga, Mumbai - 400019',
    affiliation: 'Mumbai University',
    website: 'https://vjti.ac.in',
    type: 'Government',
    streams: ['Engineering'],
    exams: ['JEE', 'CET'],
    cutoffs: { jee: 80, cet: 150, neet: null, hsc: null },
    fees: { engineering: 85000 },
    ranking: 3, rating: 4.6, established: 1887, totalSeats: 540,
    description: 'Historic engineering institution with strong industry connections in Mumbai.',
    lat: 19.0219, lng: 72.8560,
  },
  {
    name: 'Institute of Chemical Technology',
    shortName: 'ICT Mumbai',
    city: 'Mumbai', district: 'Mumbai',
    address: 'Nathalal Parekh Marg, Matunga, Mumbai - 400019',
    affiliation: 'Autonomous (Deemed University)',
    website: 'https://www.ictmumbai.edu.in',
    type: 'Deemed',
    streams: ['Engineering'],
    exams: ['JEE', 'CET'],
    cutoffs: { jee: 78, cet: 148, neet: null, hsc: null },
    fees: { engineering: 110000 },
    ranking: 4, rating: 4.5, established: 1933, totalSeats: 360,
    description: 'Leading institute for chemical engineering and technology.',
    lat: 19.0254, lng: 72.8544,
  },
  {
    name: 'Sardar Patel Institute of Technology',
    shortName: 'SPIT Mumbai',
    city: 'Mumbai', district: 'Mumbai',
    address: 'Bhavans Campus, Munshi Nagar, Andheri West, Mumbai - 400058',
    affiliation: 'Mumbai University',
    website: 'https://www.spit.ac.in',
    type: 'Autonomous',
    streams: ['Engineering'],
    exams: ['JEE', 'CET'],
    cutoffs: { jee: 72, cet: 140, neet: null, hsc: null },
    fees: { engineering: 150000 },
    ranking: 5, rating: 4.4, established: 1962, totalSeats: 360,
    description: 'Top autonomous engineering institute in Mumbai with excellent placement record.',
    lat: 19.1192, lng: 72.8366,
  },
  {
    name: 'Pune Institute of Computer Technology',
    shortName: 'PICT Pune',
    city: 'Pune', district: 'Pune',
    address: 'Survey No. 27, Near Trimurti Chowk, Dhankawadi, Pune - 411043',
    affiliation: 'Savitribai Phule Pune University',
    website: 'https://pict.edu',
    type: 'Private',
    streams: ['Engineering'],
    exams: ['JEE', 'CET'],
    cutoffs: { jee: 70, cet: 138, neet: null, hsc: null },
    fees: { engineering: 180000 },
    ranking: 6, rating: 4.4, established: 1983, totalSeats: 480,
    description: 'Renowned for CS and IT programs with 100% placement support.',
    lat: 18.4570, lng: 73.8602,
  },
  {
    name: 'MIT College of Engineering',
    shortName: 'MITCOE',
    city: 'Pune', district: 'Pune',
    address: 'MIT Campus, Paud Road, Kothrud, Pune - 411038',
    affiliation: 'Savitribai Phule Pune University',
    website: 'https://www.mitcoe.edu.in',
    type: 'Private',
    streams: ['Engineering'],
    exams: ['JEE', 'CET'],
    cutoffs: { jee: 65, cet: 130, neet: null, hsc: null },
    fees: { engineering: 200000 },
    ranking: 7, rating: 4.3, established: 1983, totalSeats: 720,
    description: 'Top ranked private engineering institute in Pune with world-class infrastructure.',
    lat: 18.5029, lng: 73.8161,
  },
  {
    name: 'Vishwakarma Institute of Technology',
    shortName: 'VIT Pune',
    city: 'Pune', district: 'Pune',
    address: '666, Upper Indira Nagar, Bibwewadi, Pune - 411037',
    affiliation: 'Savitribai Phule Pune University',
    website: 'https://www.vit.edu',
    type: 'Autonomous',
    streams: ['Engineering'],
    exams: ['JEE', 'CET'],
    cutoffs: { jee: 62, cet: 125, neet: null, hsc: null },
    fees: { engineering: 190000 },
    ranking: 8, rating: 4.2, established: 1983, totalSeats: 540,
    description: 'Autonomous status institute known for strong technical education.',
    lat: 18.4726, lng: 73.8637,
  },
  {
    name: 'KJ Somaiya College of Engineering',
    shortName: 'KJSCE Mumbai',
    city: 'Mumbai', district: 'Mumbai',
    address: 'Vidyanagar, Vidyavihar, Mumbai - 400077',
    affiliation: 'Mumbai University',
    website: 'https://kjsce.somaiya.edu',
    type: 'Private',
    streams: ['Engineering'],
    exams: ['JEE', 'CET'],
    cutoffs: { jee: 68, cet: 132, neet: null, hsc: null },
    fees: { engineering: 210000 },
    ranking: 9, rating: 4.3, established: 1983, totalSeats: 540,
    description: 'Prestigious campus in Mumbai with strong alumni network.',
    lat: 19.0785, lng: 72.9035,
  },
  {
    name: 'LGD Amravati University Institute of Engineering',
    shortName: 'SGBAU',
    city: 'Amravati', district: 'Amravati',
    address: 'Tapovan Road, Amravati - 444602',
    affiliation: 'Sant Gadge Baba Amravati University',
    website: 'https://www.sgbau.ac.in',
    type: 'Government',
    streams: ['Engineering'],
    exams: ['CET'],
    cutoffs: { jee: null, cet: 85, neet: null, hsc: null },
    fees: { engineering: 55000 },
    ranking: 20, rating: 3.8, established: 1983, totalSeats: 360,
    description: 'Government engineering institute serving students from Vidarbha region.',
    lat: 20.9320, lng: 77.7523,
  },
  {
    name: 'Government College of Engineering Aurangabad',
    shortName: 'GCEA',
    city: 'Aurangabad', district: 'Aurangabad',
    address: 'Station Road, Aurangabad - 431005',
    affiliation: 'Dr. Babasaheb Ambedkar Marathwada University',
    website: 'https://www.geca.ac.in',
    type: 'Government',
    streams: ['Engineering'],
    exams: ['JEE', 'CET'],
    cutoffs: { jee: 55, cet: 110, neet: null, hsc: null },
    fees: { engineering: 65000 },
    ranking: 15, rating: 4.0, established: 1960, totalSeats: 420,
    description: 'Premier government engineering college in Marathwada region.',
    lat: 19.8785, lng: 75.3432,
  },
  {
    name: 'Government College of Engineering Nagpur',
    shortName: 'GCEN',
    city: 'Nagpur', district: 'Nagpur',
    address: 'Seminary Hills, Nagpur - 440001',
    affiliation: 'Rashtrasant Tukadoji Maharaj Nagpur University',
    website: 'https://gcoeng.ac.in',
    type: 'Government',
    streams: ['Engineering'],
    exams: ['JEE', 'CET'],
    cutoffs: { jee: 58, cet: 115, neet: null, hsc: null },
    fees: { engineering: 60000 },
    ranking: 13, rating: 4.1, established: 1960, totalSeats: 480,
    description: 'Top government engineering college in Vidarbha region.',
    lat: 21.1458, lng: 79.0882,
  },
  {
    name: 'Symbiosis Institute of Technology',
    shortName: 'SIT Pune',
    city: 'Pune', district: 'Pune',
    address: 'Symbiosis International University, Lavale, Pune - 412115',
    affiliation: 'Symbiosis International University',
    website: 'https://www.sitpune.edu.in',
    type: 'Deemed',
    streams: ['Engineering'],
    exams: ['JEE', 'CET'],
    cutoffs: { jee: 60, cet: 118, neet: null, hsc: null },
    fees: { engineering: 280000 },
    ranking: 11, rating: 4.2, established: 2008, totalSeats: 360,
    description: 'Modern engineering institute with cutting-edge labs and great placements.',
    lat: 18.5697, lng: 73.7294,
  },
  {
    name: 'Walchand College of Engineering',
    shortName: 'WCE Sangli',
    city: 'Sangli', district: 'Sangli',
    address: 'Vishrambag, Sangli - 416415',
    affiliation: 'Shivaji University',
    website: 'https://www.walchandsangli.ac.in',
    type: 'Government',
    streams: ['Engineering'],
    exams: ['JEE', 'CET'],
    cutoffs: { jee: 55, cet: 112, neet: null, hsc: null },
    fees: { engineering: 70000 },
    ranking: 16, rating: 4.0, established: 1947, totalSeats: 420,
    description: 'Historic engineering college with strong industrial connections in western Maharashtra.',
    lat: 16.8572, lng: 74.5815,
  },
  {
    name: 'Rajarambapu Institute of Technology',
    shortName: 'RIT Islampur',
    city: 'Islampur', district: 'Sangli',
    address: 'Rajaramnagar, Islampur - 415414',
    affiliation: 'Shivaji University',
    website: 'https://www.ritindia.edu',
    type: 'Private',
    streams: ['Engineering'],
    exams: ['CET'],
    cutoffs: { jee: null, cet: 100, neet: null, hsc: null },
    fees: { engineering: 120000 },
    ranking: 22, rating: 4.0, established: 1983, totalSeats: 540,
    description: 'Well-equipped private engineering college with good placement record.',
    lat: 17.0581, lng: 74.2601,
  },

  // ─── MEDICAL - NEET ───────────────────────────────────────────────────
  {
    name: 'Grant Medical College & Sir JJ Group of Hospitals',
    shortName: 'GMC Mumbai',
    city: 'Mumbai', district: 'Mumbai',
    address: 'Byculla, Mumbai - 400008',
    affiliation: 'Maharashtra University of Health Sciences',
    website: 'https://www.grantmedicalcollege.org',
    type: 'Government',
    streams: ['Medical'],
    exams: ['NEET'],
    cutoffs: { jee: null, cet: null, neet: 640, hsc: null },
    fees: { medical: 35000 },
    ranking: 1, rating: 4.8, established: 1845, totalSeats: 200,
    description: 'One of the oldest and most prestigious medical colleges in India.',
    lat: 18.9735, lng: 72.8283,
  },
  {
    name: 'Seth G.S. Medical College & KEM Hospital',
    shortName: 'KEM Hospital',
    city: 'Mumbai', district: 'Mumbai',
    address: 'Parel, Mumbai - 400012',
    affiliation: 'Maharashtra University of Health Sciences',
    website: 'https://www.kem.edu',
    type: 'Government',
    streams: ['Medical'],
    exams: ['NEET'],
    cutoffs: { jee: null, cet: null, neet: 645, hsc: null },
    fees: { medical: 35000 },
    ranking: 2, rating: 4.8, established: 1926, totalSeats: 200,
    description: 'Premier medical college affiliated to the iconic KEM Hospital.',
    lat: 19.0010, lng: 72.8403,
  },
  {
    name: 'B.J. Medical College',
    shortName: 'BJMC Pune',
    city: 'Pune', district: 'Pune',
    address: 'Sassoon Road, Pune - 411001',
    affiliation: 'Maharashtra University of Health Sciences',
    website: 'https://www.bjmc.edu.in',
    type: 'Government',
    streams: ['Medical'],
    exams: ['NEET'],
    cutoffs: { jee: null, cet: null, neet: 630, hsc: null },
    fees: { medical: 35000 },
    ranking: 3, rating: 4.7, established: 1946, totalSeats: 250,
    description: 'Top government medical college in Pune with Sassoon Hospital attachment.',
    lat: 18.5196, lng: 73.8554,
  },
  {
    name: 'Lokmanya Tilak Municipal Medical College',
    shortName: 'Sion Hospital',
    city: 'Mumbai', district: 'Mumbai',
    address: 'Sion, Mumbai - 400022',
    affiliation: 'Maharashtra University of Health Sciences',
    website: 'https://www.ltmmc.edu.in',
    type: 'Government',
    streams: ['Medical'],
    exams: ['NEET'],
    cutoffs: { jee: null, cet: null, neet: 620, hsc: null },
    fees: { medical: 35000 },
    ranking: 4, rating: 4.6, established: 1964, totalSeats: 150,
    description: 'Reputed municipal medical college attached to Sion Hospital.',
    lat: 19.0390, lng: 72.8619,
  },
  {
    name: 'Government Medical College Nagpur',
    shortName: 'GMC Nagpur',
    city: 'Nagpur', district: 'Nagpur',
    address: 'Medical Square, Nagpur - 440009',
    affiliation: 'Maharashtra University of Health Sciences',
    website: 'https://www.gmcnagpur.ac.in',
    type: 'Government',
    streams: ['Medical'],
    exams: ['NEET'],
    cutoffs: { jee: null, cet: null, neet: 600, hsc: null },
    fees: { medical: 35000 },
    ranking: 5, rating: 4.5, established: 1947, totalSeats: 200,
    description: 'Premier medical college serving Vidarbha region.',
    lat: 21.1498, lng: 79.0849,
  },
  {
    name: 'Government Medical College Aurangabad',
    shortName: 'GMC Aurangabad',
    city: 'Aurangabad', district: 'Aurangabad',
    address: 'Jubilee Park, Aurangabad - 431001',
    affiliation: 'Maharashtra University of Health Sciences',
    website: 'https://gmcaurangabad.org',
    type: 'Government',
    streams: ['Medical'],
    exams: ['NEET'],
    cutoffs: { jee: null, cet: null, neet: 590, hsc: null },
    fees: { medical: 35000 },
    ranking: 6, rating: 4.3, established: 1956, totalSeats: 150,
    description: 'Leading government medical institution in Marathwada region.',
    lat: 19.8762, lng: 75.3433,
  },
  {
    name: 'Dr. DY Patil Medical College',
    shortName: 'DY Patil Medical',
    city: 'Pune', district: 'Pune',
    address: 'Sant Tukaram Nagar, Pimpri, Pune - 411018',
    affiliation: 'Dr. DY Patil Deemed University',
    website: 'https://www.dypatil.edu',
    type: 'Deemed',
    streams: ['Medical', 'Pharmacy'],
    exams: ['NEET'],
    cutoffs: { jee: null, cet: null, neet: 550, hsc: null },
    fees: { medical: 1200000, pharmacy: 150000 },
    ranking: 10, rating: 4.1, established: 1996, totalSeats: 150,
    description: 'Well-equipped private medical college with state-of-the-art hospital.',
    lat: 18.6271, lng: 73.8007,
  },
  {
    name: 'Symbiosis Medical College for Women',
    shortName: 'SMCW Pune',
    city: 'Pune', district: 'Pune',
    address: 'Lavale, Mulshi, Pune - 412115',
    affiliation: 'Symbiosis International University',
    website: 'https://smcw.siu.edu.in',
    type: 'Deemed',
    streams: ['Medical'],
    exams: ['NEET'],
    cutoffs: { jee: null, cet: null, neet: 560, hsc: null },
    fees: { medical: 1400000 },
    ranking: 12, rating: 4.0, established: 2019, totalSeats: 100,
    description: 'India\'s first all-women medical college with modern facilities.',
    lat: 18.5697, lng: 73.7294,
  },

  // ─── ARTS / SCIENCE / COMMERCE - HSC ─────────────────────────────────
  {
    name: 'Fergusson College',
    shortName: 'Fergusson',
    city: 'Pune', district: 'Pune',
    address: 'Fergusson College Road, Shivajinagar, Pune - 411004',
    affiliation: 'Savitribai Phule Pune University',
    website: 'https://www.fergusson.edu',
    type: 'Autonomous',
    streams: ['Science', 'Commerce', 'Arts'],
    exams: ['HSC'],
    cutoffs: { jee: null, cet: null, neet: null, hsc: 80 },
    fees: { science: 25000, commerce: 20000, arts: 18000 },
    ranking: 1, rating: 4.7, established: 1885, totalSeats: 1200,
    description: 'One of the oldest and most coveted liberal arts and science colleges in India.',
    lat: 18.5220, lng: 73.8397,
  },
  {
    name: 'St. Xavier\'s College Mumbai',
    shortName: 'Xavier\'s Mumbai',
    city: 'Mumbai', district: 'Mumbai',
    address: '5, Mahapalika Marg, Mumbai - 400001',
    affiliation: 'Mumbai University',
    website: 'https://www.xaviers.edu',
    type: 'Autonomous',
    streams: ['Science', 'Commerce', 'Arts'],
    exams: ['HSC'],
    cutoffs: { jee: null, cet: null, neet: null, hsc: 85 },
    fees: { science: 30000, commerce: 25000, arts: 22000 },
    ranking: 2, rating: 4.8, established: 1869, totalSeats: 1500,
    description: 'Iconic autonomous institution known for academic excellence and vibrant campus life.',
    lat: 18.9382, lng: 72.8314,
  },
  {
    name: 'Elphinstone College',
    shortName: 'Elphinstone',
    city: 'Mumbai', district: 'Mumbai',
    address: '1, Mahapalika Marg, Fort, Mumbai - 400032',
    affiliation: 'Mumbai University',
    website: 'https://www.elphinstonecollege.ac.in',
    type: 'Government',
    streams: ['Science', 'Arts', 'Commerce'],
    exams: ['HSC'],
    cutoffs: { jee: null, cet: null, neet: null, hsc: 75 },
    fees: { science: 12000, commerce: 10000, arts: 9000 },
    ranking: 3, rating: 4.5, established: 1856, totalSeats: 1000,
    description: 'Historic government college with excellent faculty and affordable education.',
    lat: 18.9356, lng: 72.8312,
  },
  {
    name: 'Symbiosis College of Arts and Commerce',
    shortName: 'SCAC Pune',
    city: 'Pune', district: 'Pune',
    address: 'Senapati Bapat Road, Pune - 411004',
    affiliation: 'Savitribai Phule Pune University',
    website: 'https://www.symbiosisCACpune.com',
    type: 'Private',
    streams: ['Arts', 'Commerce'],
    exams: ['HSC'],
    cutoffs: { jee: null, cet: null, neet: null, hsc: 70 },
    fees: { commerce: 45000, arts: 40000 },
    ranking: 5, rating: 4.3, established: 1983, totalSeats: 800,
    description: 'Popular college with vibrant campus life and excellent commerce programs.',
    lat: 18.5204, lng: 73.8346,
  },
  {
    name: 'Institute of Science Mumbai',
    shortName: 'IS Mumbai',
    city: 'Mumbai', district: 'Mumbai',
    address: '15, Madame Cama Road, Mumbai - 400032',
    affiliation: 'Mumbai University',
    website: 'https://www.ismu.ac.in',
    type: 'Government',
    streams: ['Science'],
    exams: ['HSC'],
    cutoffs: { jee: null, cet: null, neet: null, hsc: 78 },
    fees: { science: 15000 },
    ranking: 4, rating: 4.4, established: 1920, totalSeats: 600,
    description: 'Top science college in Mumbai with excellent research facilities.',
    lat: 18.9337, lng: 72.8283,
  },
  {
    name: 'Brihan Maharashtra College of Commerce',
    shortName: 'BMCC Pune',
    city: 'Pune', district: 'Pune',
    address: 'Senapati Bapat Road, Pune - 411004',
    affiliation: 'Savitribai Phule Pune University',
    website: 'https://bmcc.ac.in',
    type: 'Private',
    streams: ['Commerce', 'Arts'],
    exams: ['HSC'],
    cutoffs: { jee: null, cet: null, neet: null, hsc: 65 },
    fees: { commerce: 30000, arts: 25000 },
    ranking: 6, rating: 4.2, established: 1943, totalSeats: 1800,
    description: 'Largest commerce college in Pune with strong alumni network.',
    lat: 18.5200, lng: 73.8380,
  },
  {
    name: 'Ruparel College',
    shortName: 'Ruparel',
    city: 'Mumbai', district: 'Mumbai',
    address: 'Senapati Bapat Marg, Matunga West, Mumbai - 400016',
    affiliation: 'Mumbai University',
    website: 'https://ruparelcollege.org',
    type: 'Private',
    streams: ['Science', 'Commerce', 'Arts'],
    exams: ['HSC'],
    cutoffs: { jee: null, cet: null, neet: null, hsc: 80 },
    fees: { science: 28000, commerce: 22000, arts: 18000 },
    ranking: 7, rating: 4.3, established: 1958, totalSeats: 1200,
    description: 'Reputed college known for science and commerce with active extracurriculars.',
    lat: 19.0276, lng: 72.8447,
  },
  {
    name: 'Shivaji University',
    shortName: 'SUK Kolhapur',
    city: 'Kolhapur', district: 'Kolhapur',
    address: 'Vidyanagar, Kolhapur - 416004',
    affiliation: 'Shivaji University',
    website: 'https://www.unishivaji.ac.in',
    type: 'Government',
    streams: ['Science', 'Commerce', 'Arts', 'Management'],
    exams: ['HSC'],
    cutoffs: { jee: null, cet: null, neet: null, hsc: 60 },
    fees: { science: 18000, commerce: 15000, arts: 12000, management: 40000 },
    ranking: 8, rating: 4.0, established: 1962, totalSeats: 2000,
    description: 'State university offering wide range of UG and PG programs at affordable fees.',
    lat: 16.7050, lng: 74.2433,
  },
  {
    name: 'Laxminarayan Institute of Technology',
    shortName: 'LIT Nagpur',
    city: 'Nagpur', district: 'Nagpur',
    address: 'Amravati Road, Nagpur - 440010',
    affiliation: 'Rashtrasant Tukadoji Maharaj Nagpur University',
    website: 'https://www.litnagpur.ac.in',
    type: 'Government',
    streams: ['Engineering'],
    exams: ['CET'],
    cutoffs: { jee: null, cet: 105, neet: null, hsc: null },
    fees: { engineering: 58000 },
    ranking: 18, rating: 3.9, established: 1942, totalSeats: 360,
    description: 'Established engineering institute with focus on applied sciences.',
    lat: 21.1327, lng: 79.0510,
  },
  {
    name: 'Nashik Engineering Cluster',
    shortName: 'NEC Nashik',
    city: 'Nashik', district: 'Nashik',
    address: 'Trimbak Road, Nashik - 422013',
    affiliation: 'Savitribai Phule Pune University',
    website: 'https://www.necnashik.org',
    type: 'Private',
    streams: ['Engineering'],
    exams: ['CET'],
    cutoffs: { jee: null, cet: 90, neet: null, hsc: null },
    fees: { engineering: 95000 },
    ranking: 25, rating: 3.8, established: 1985, totalSeats: 480,
    description: 'Engineering college serving the rapidly growing industrial hub of Nashik.',
    lat: 19.9975, lng: 73.7898,
  },
  {
    name: 'Dr. Babasaheb Ambedkar Technological University',
    shortName: 'DBATU Lonere',
    city: 'Lonere', district: 'Raigad',
    address: 'Lonere, Raigad - 402103',
    affiliation: 'Autonomous (State University)',
    website: 'https://www.dbatu.ac.in',
    type: 'Government',
    streams: ['Engineering'],
    exams: ['JEE', 'CET'],
    cutoffs: { jee: 50, cet: 100, neet: null, hsc: null },
    fees: { engineering: 55000 },
    ranking: 17, rating: 4.0, established: 1989, totalSeats: 600,
    description: 'State technical university with focus on affordable quality engineering education.',
    lat: 18.2714, lng: 73.0983,
  },
  {
    name: 'Solapur University',
    shortName: 'SU Solapur',
    city: 'Solapur', district: 'Solapur',
    address: 'Kegaon, Solapur - 413255',
    affiliation: 'Solapur University',
    website: 'https://su.digitaluniversity.ac',
    type: 'Government',
    streams: ['Science', 'Commerce', 'Arts'],
    exams: ['HSC'],
    cutoffs: { jee: null, cet: null, neet: null, hsc: 55 },
    fees: { science: 14000, commerce: 12000, arts: 10000 },
    ranking: 30, rating: 3.7, established: 2004, totalSeats: 1500,
    description: 'State university serving students from Solapur and surrounding districts.',
    lat: 17.6856, lng: 75.9013,
  },
  {
    name: 'MES College of Engineering',
    shortName: 'MESCE Pune',
    city: 'Pune', district: 'Pune',
    address: 'Survey No. 4, Wadia College Road, Pune - 411001',
    affiliation: 'Savitribai Phule Pune University',
    website: 'https://www.mescoe.com',
    type: 'Private',
    streams: ['Engineering'],
    exams: ['CET'],
    cutoffs: { jee: null, cet: 95, neet: null, hsc: null },
    fees: { engineering: 110000 },
    ranking: 24, rating: 3.8, established: 1985, totalSeats: 360,
    description: 'Engineering college with good industry connections and extracurricular focus.',
    lat: 18.5302, lng: 73.8757,
  },
];

async function seedDB() {
  try {
    console.log('🔌 Connecting to MongoDB Atlas...');
    await mongoose.connect(MONGO_URI);
    console.log('✅ Connected to MongoDB Atlas');

    await College.deleteMany({});
    console.log('🗑️  Cleared existing colleges');

    const inserted = await College.insertMany(colleges);
    console.log(`🎉 Successfully seeded ${inserted.length} colleges!`);

    await mongoose.disconnect();
    console.log('🔌 Disconnected from MongoDB');
    process.exit(0);
  } catch (err) {
    console.error('❌ Seed error:', err);
    process.exit(1);
  }
}

seedDB();
